baseURL = "https://example.com"

languageCode = "ja"
DefaultContentLanguage = "ja"
title = "Japlengs Wiki"
theme = "techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]

    # Source Code repository section
    description = "開発・勉強共有のGitHub"
    github_repository = "https://github.com/japlengs"
    version = "0.0.1"

    title = "Japlengs"
    images = ["images/og-image.png"]
    custom_font_color = "#ffffff"
    custom_background_color = "#772222"
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar
    dateformat = "" # default "2 Jan 2006"
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]
    algolia_search_enable = false
    algolia_indexName = "japlengs-doc"
    algolia_appId = ""
    algolia_apiKey = "" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Twitter"
        url = "https://twitter.com/thingsym"
        weight = 2

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
